# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stacked_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        StackedWidget.setObjectName("StackedWidget")
        StackedWidget.resize(742, 504)
        StackedWidget.setMinimumSize(QtCore.QSize(742, 504))
        StackedWidget.setMaximumSize(QtCore.QSize(742, 504))
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.widget_3 = QtWidgets.QWidget(self.page_1)
        self.widget_3.setGeometry(QtCore.QRect(370, 0, 371, 501))
        self.widget_3.setStyleSheet("QWidget {\n"
"    background-color: #a6a6a6; /* Lichtere versie van #4549a0 */\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.verberg_page1 = QtWidgets.QPushButton(self.widget_3)
        self.verberg_page1.setGeometry(QtCore.QRect(270, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        self.verberg_page1.setFont(font)
        self.verberg_page1.setStyleSheet("QPushButton {\n"
"    border: none;  /* Verwijder de rand */\n"
"    background-color: #4549a0;  /* Stel de achtergrondkleur in op #4549a0 */\n"
"    color: white;  /* Zet de tekstkleur op wit voor de geselecteerde tekst */\n"
"    padding: 5px;  /* Voeg wat padding toe voor de tekst */\n"
"    border-radius: 5px;  /* Maak de hoeken van de QComboBox iets ronder */\n"
"}")
        self.verberg_page1.setObjectName("verberg_page1")
        self.close_page1 = QtWidgets.QPushButton(self.widget_3)
        self.close_page1.setGeometry(QtCore.QRect(320, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        self.close_page1.setFont(font)
        self.close_page1.setStyleSheet("QPushButton {\n"
"    border: none;  /* Verwijder de rand */\n"
"    background-color: #4549a0;  /* Stel de achtergrondkleur in op #4549a0 */\n"
"    color: white;  /* Zet de tekstkleur op wit voor de geselecteerde tekst */\n"
"    padding: 5px;  /* Voeg wat padding toe voor de tekst */\n"
"    border-radius: 5px;  /* Maak de hoeken van de QComboBox iets ronder */\n"
"}")
        self.close_page1.setObjectName("close_page1")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(30, 60, 221, 71))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.naam_input = QtWidgets.QLineEdit(self.widget_3)
        self.naam_input.setGeometry(QtCore.QRect(30, 120, 161, 51))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(12)
        self.naam_input.setFont(font)
        self.naam_input.setStyleSheet("QLineEdit {\n"
"    border: none;  /* Verwijder de rand */\n"
"    background-color: #4549a0;  /* Stel de achtergrondkleur in op #4549a0 */\n"
"    color: white;  /* Zet de tekstkleur op wit voor de ingevulde tekst */\n"
"    padding: 5px;  /* Voeg wat padding toe voor de tekst */\n"
"    border-radius: 5px;  /* Maak de hoeken van de QLineEdit iets ronder */\n"
"}\n"
"\n"
"/* Stel de kleur van de placeholder-tekst in */\n"
"QLineEdit::placeholder \n"
"")
        self.naam_input.setObjectName("naam_input")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(30, 200, 221, 71))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.onderwerp_input = QtWidgets.QComboBox(self.widget_3)
        self.onderwerp_input.setGeometry(QtCore.QRect(30, 260, 161, 51))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(12)
        self.onderwerp_input.setFont(font)
        self.onderwerp_input.setStyleSheet("QComboBox {\n"
"    border: none;  /* Verwijder de rand */\n"
"    background-color: #4549a0;  /* Stel de achtergrondkleur in op #4549a0 */\n"
"    color: white;  /* Zet de tekstkleur op wit voor de geselecteerde tekst */\n"
"    padding: 5px;  /* Voeg wat padding toe voor de tekst */\n"
"    border-radius: 5px;  /* Maak de hoeken van de QComboBox iets ronder */\n"
"    \n"
"}\n"
"\n"
"/* Stel de kleur van de placeholder-tekst in */\n"
"QComboBox::drop-down {\n"
"    border: none;  /* Verwijder de rand van het dropdownmenu */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #4549a0;  /* Stel de achtergrondkleur in van de dropdownlijst */\n"
"    color: white;  /* Zet de tekstkleur in de dropdownlijst op wit */\n"
"}\n"
"\n"
"/* Als er een placeholder tekst is (bijvoorbeeld \"Kies een optie\") */\n"
"QComboBox::item {\n"
"    color: #d3d3d3;  /* Lichte grijze kleur voor de niet-geselecteerde items in de lijst */\n"
"}\n"
"\n"
"")
        self.onderwerp_input.setObjectName("onderwerp_input")
        self.onderwerp_input.addItem("")
        self.onderwerp_input.addItem("")
        self.onderwerp_input.addItem("")
        self.onderwerp_input.addItem("")
        self.onderwerp_input.addItem("")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(30, 360, 161, 61))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.moeilijkheid_input = QtWidgets.QComboBox(self.widget_3)
        self.moeilijkheid_input.setGeometry(QtCore.QRect(30, 420, 161, 51))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(12)
        self.moeilijkheid_input.setFont(font)
        self.moeilijkheid_input.setStyleSheet("QComboBox {\n"
"    border: none;  /* Verwijder de rand */\n"
"    background-color: #4549a0;  /* Stel de achtergrondkleur in op #4549a0 */\n"
"    color: white;  /* Zet de tekstkleur op wit voor de geselecteerde tekst */\n"
"    padding: 5px;  /* Voeg wat padding toe voor de tekst */\n"
"    border-radius: 5px;  /* Maak de hoeken van de QComboBox iets ronder */\n"
"    \n"
"}\n"
"\n"
"/* Stel de kleur van de placeholder-tekst in */\n"
"QComboBox::drop-down {\n"
"    border: none;  /* Verwijder de rand van het dropdownmenu */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #4549a0;  /* Stel de achtergrondkleur in van de dropdownlijst */\n"
"    color: white;  /* Zet de tekstkleur in de dropdownlijst op wit */\n"
"}\n"
"\n"
"/* Als er een placeholder tekst is (bijvoorbeeld \"Kies een optie\") */\n"
"QComboBox::item {\n"
"    color: #d3d3d3;  /* Lichte grijze kleur voor de niet-geselecteerde items in de lijst */\n"
"}\n"
"\n"
"")
        self.moeilijkheid_input.setObjectName("moeilijkheid_input")
        self.moeilijkheid_input.addItem("")
        self.moeilijkheid_input.addItem("")
        self.moeilijkheid_input.addItem("")
        self.moeilijkheid_input.addItem("")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(210, 360, 161, 61))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setGeometry(QtCore.QRect(10, 340, 361, 5))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    background-color: #FDF5E6; /* Maakt de QLabel een dikke zwarte balk */\n"
"    min-height: 5px; /* Dikte van de lijn */\n"
"    max-height: 5px;\n"
"}\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 361, 5))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    background-color: #FDF5E6; /* Maakt de QLabel een dikke zwarte balk */\n"
"    min-height: 5px; /* Dikte van de lijn */\n"
"    max-height: 5px;\n"
"}\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setGeometry(QtCore.QRect(10, 190, 361, 5))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    background-color: #FDF5E6; /* Maakt de QLabel een dikke zwarte balk */\n"
"    min-height: 5px; /* Dikte van de lijn */\n"
"    max-height: 5px;\n"
"}\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.comboBox = QtWidgets.QComboBox(self.widget_3)
        self.comboBox.setGeometry(QtCore.QRect(250, 430, 81, 31))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    border: 2px solid #a9a9a9;  /* Dunne klassieke rand */\n"
"    background-color: #FDF5E6;  /* Zelfde achtergrondkleur */\n"
"    color: #4549a0;  /* Zelfde tekstkleur */\n"
"    padding: 5px 10px;  /* Extra padding voor een luchtiger gevoel */\n"
"    border-radius: 5px;  /* Afgeronde hoeken */\n"
"    \n"
"    \n"
"    text-align: center;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setGeometry(QtCore.QRect(220, 200, 160, 71))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.willeukerig = QtWidgets.QRadioButton(self.widget_3)
        self.willeukerig.setGeometry(QtCore.QRect(270, 270, 81, 20))
        self.willeukerig.setText("")
        self.willeukerig.setObjectName("willeukerig")
        self.verberg_page1.raise_()
        self.close_page1.raise_()
        self.label.raise_()
        self.naam_input.raise_()
        self.label_2.raise_()
        self.onderwerp_input.raise_()
        self.label_3.raise_()
        self.moeilijkheid_input.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.comboBox.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.willeukerig.raise_()
        self.widget = QtWidgets.QWidget(self.page_1)
        self.widget.setGeometry(QtCore.QRect(0, 0, 381, 501))
        self.widget.setStyleSheet("QWidget {\n"
"    background-image: url(\"images/download.jpg\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: cover;  /* Zorgt ervoor dat de afbeelding de hele achtergrond bedekt */\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(40, 10, 351, 191))
        self.widget_2.setStyleSheet("QWidget {\n"
"    background-image: url(\'images/simple_logo.png\');\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: contain;  /* Zorgt ervoor dat de afbeelding volledig zichtbaar is zonder vergroting */\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.start_quiz2 = QtWidgets.QPushButton(self.widget)
        self.start_quiz2.setGeometry(QtCore.QRect(130, 250, 71, 51))
        self.start_quiz2.setStyleSheet("QPushButton {\n"
"    border: none;  /* Geen rand */\n"
"    background-color: transparent; /* Transparante achtergrond */\n"
"    background-image: url(\"images/pushbutton_app.jpg\"); /* Afbeelding */\n"
"    background-repeat: no-repeat; /* Voorkomt herhaling */\n"
"    background-position: center; /* Centreert de afbeelding */\n"
"    background-size: contain; /* Past afbeelding aan zonder te vervormen */\n"
"    border-radius: 20px; /* Afgeronde hoeken */\n"
"    padding: 10px; /* Extra ruimte rondom tekst */\n"
"    font-size: 16px; /* Tekstgrootte */\n"
"    font-weight: bold;\n"
"    color: white; /* Tekstkleur */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    opacity: 0.8; /* Iets transparanter bij hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 0.2); /* Donkere overlay bij klikken */\n"
"}\n"
"")
        self.start_quiz2.setText("")
        self.start_quiz2.setObjectName("start_quiz2")
        StackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.widget_4 = QtWidgets.QWidget(self.page_2)
        self.widget_4.setGeometry(QtCore.QRect(0, 0, 741, 221))
        self.widget_4.setStyleSheet("QWidget {\n"
"    background-color: black;  /* Lichtere versie van #4549a0 */\n"
"}\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setGeometry(QtCore.QRect(13, 24, 231, 131))
        self.widget_5.setStyleSheet("QWidget {\n"
"    background-image: url(\"images/quizlerapp_smalllogo.jpg\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: contain;  /* Zorgt ervoor dat de afbeelding volledig zichtbaar is zonder vervorming */\n"
"}\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.verberg_page2 = QtWidgets.QPushButton(self.widget_4)
        self.verberg_page2.setGeometry(QtCore.QRect(640, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        self.verberg_page2.setFont(font)
        self.verberg_page2.setStyleSheet("QPushButton {\n"
"    background-color: #6a6db6;  /* Lichtere versie van #4549a0 */\n"
"}\n"
"")
        self.verberg_page2.setObjectName("verberg_page2")
        self.close_page2 = QtWidgets.QPushButton(self.widget_4)
        self.close_page2.setGeometry(QtCore.QRect(690, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        self.close_page2.setFont(font)
        self.close_page2.setStyleSheet("QPushButton {\n"
"    background-color: #6a6db6;  /* Lichtere versie van #4549a0 */\n"
"}\n"
"")
        self.close_page2.setObjectName("close_page2")
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        self.label_9.setGeometry(QtCore.QRect(0, 210, 741, 5))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"    background-color: #a6a6a6; /* Maakt de QLabel een dikke zwarte balk */\n"
"    min-height: 5px; /* Dikte van de lijn */\n"
"    max-height: 5px;\n"
"}\n"
"")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.next_vraag = QtWidgets.QPushButton(self.widget_4)
        self.next_vraag.setGeometry(QtCore.QRect(330, 107, 71, 51))
        self.next_vraag.setStyleSheet("QPushButton {\n"
"    border: none;  /* Geen rand */\n"
"    background-color: transparent; /* Transparante achtergrond */\n"
"    background-image: url(\"images/pushbutton_app.jpg\"); /* Afbeelding */\n"
"    background-repeat: no-repeat; /* Voorkomt herhaling */\n"
"    background-position: center; /* Centreert de afbeelding */\n"
"    background-size: contain; /* Past afbeelding aan zonder te vervormen */\n"
"    border-radius: 20px; /* Afgeronde hoeken */\n"
"    padding: 10px; /* Extra ruimte rondom tekst */\n"
"    font-size: 16px; /* Tekstgrootte */\n"
"    font-weight: bold;\n"
"    color: white; /* Tekstkleur */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    opacity: 0.8; /* Iets transparanter bij hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 0.2); /* Donkere overlay bij klikken */\n"
"}\n"
"")
        self.next_vraag.setText("")
        self.next_vraag.setObjectName("next_vraag")
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        self.label_10.setGeometry(QtCore.QRect(0, 200, 741, 5))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel {\n"
"    background-color: #a6a6a6; /* Maakt de QLabel een dikke zwarte balk */\n"
"    min-height: 5px; /* Dikte van de lijn */\n"
"    max-height: 5px;\n"
"}\n"
"")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.widget_6 = QtWidgets.QWidget(self.page_2)
        self.widget_6.setGeometry(QtCore.QRect(0, 200, 741, 321))
        self.widget_6.setStyleSheet("QWidget {\n"
"    background-color: #6a6db6;  /* Lichtere versie van #4549a0 */\n"
"}\n"
"\n"
"")
        self.widget_6.setObjectName("widget_6")
        self.vraag_input = QtWidgets.QLabel(self.widget_6)
        self.vraag_input.setGeometry(QtCore.QRect(10, 20, 681, 101))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(16)
        self.vraag_input.setFont(font)
        self.vraag_input.setStyleSheet("QLabel {\n"
"    border: none;  /* Verwijder de rand */\n"
"\n"
"    color: white; /* Zet de tekstkleur op wit voor de ingevulde tekst */\n"
"    padding: 5px;  /* Voeg wat padding toe voor de tekst */\n"
"    border-radius: 5px;  /* Maak de hoeken van de QLineEdit iets ronder */\n"
"}")
        self.vraag_input.setText("")
        self.vraag_input.setWordWrap(True)
        self.vraag_input.setObjectName("vraag_input")
        self.optie_input = QtWidgets.QListWidget(self.widget_6)
        self.optie_input.setGeometry(QtCore.QRect(10, 150, 681, 141))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(16)
        self.optie_input.setFont(font)
        self.optie_input.setStyleSheet("QListWidget {\n"
"    border: none;  /* Verwijder de rand */\n"
"\n"
"    color: black;  /* Zet de tekstkleur op wit voor de ingevulde tekst */\n"
"    padding: 5px;  /* Voeg wat padding toe voor de tekst */\n"
"    border-radius: 5px;  /* Maak de hoeken van de QLineEdit iets ronder */\n"
"}")
        self.optie_input.setWordWrap(True)
        self.optie_input.setObjectName("optie_input")
        self.widget_6.raise_()
        self.widget_4.raise_()
        StackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.widget_7 = QtWidgets.QWidget(self.page_3)
        self.widget_7.setGeometry(QtCore.QRect(0, 0, 741, 211))
        self.widget_7.setStyleSheet("QWidget {\n"
"    background-color: black;  /* Lichtere versie van #4549a0 */\n"
"}\n"
"")
        self.widget_7.setObjectName("widget_7")
        self.verberg_page3 = QtWidgets.QPushButton(self.widget_7)
        self.verberg_page3.setGeometry(QtCore.QRect(640, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        self.verberg_page3.setFont(font)
        self.verberg_page3.setStyleSheet("QPushButton {\n"
"    background-color: #6a6db6;  /* Lichtere versie van #4549a0 */\n"
"}\n"
"")
        self.verberg_page3.setObjectName("verberg_page3")
        self.close_page3 = QtWidgets.QPushButton(self.widget_7)
        self.close_page3.setGeometry(QtCore.QRect(690, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        self.close_page3.setFont(font)
        self.close_page3.setStyleSheet("QPushButton {\n"
"    background-color: #6a6db6;  /* Lichtere versie van #4549a0 */\n"
"}\n"
"")
        self.close_page3.setObjectName("close_page3")
        self.widget_8 = QtWidgets.QWidget(self.widget_7)
        self.widget_8.setGeometry(QtCore.QRect(-7, 10, 241, 161))
        self.widget_8.setStyleSheet("QWidget {\n"
"    background-image: url(\"images/scoreboard_quizapp.jpg\");\n"

"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: cover;  /* Zorgt ervoor dat de afbeelding de hele achtergrond vult */\n"
"}\n"
"")
        self.widget_8.setObjectName("widget_8")
        self.feedback_button = QtWidgets.QPushButton(self.widget_7)
        self.feedback_button.setGeometry(QtCore.QRect(568, 98, 81, 71))
        self.feedback_button.setStyleSheet("QPushButton {\n"
"    background-image: url(\"images/feedback_logo.jpg\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: cover;  /* Zorgt ervoor dat de afbeelding de hele achtergrond vult */\n"
"}")
        self.feedback_button.setText("")
        self.feedback_button.setObjectName("feedback_button")
        self.herstart_quiz = QtWidgets.QPushButton(self.widget_7)
        self.herstart_quiz.setGeometry(QtCore.QRect(330, 108, 71, 51))
        self.herstart_quiz.setStyleSheet("QPushButton {\n"
"    border: none;  /* Geen rand */\n"
"    background-color: transparent; /* Transparante achtergrond */\n"
"    background-image: url(\"images/pushbutton_app.jpg\"); /* Afbeelding */\n"
"    background-repeat: no-repeat; /* Voorkomt herhaling */\n"
"    background-position: center; /* Centreert de afbeelding */\n"
"    background-size: contain; /* Past afbeelding aan zonder te vervormen */\n"
"    border-radius: 20px; /* Afgeronde hoeken */\n"
"    padding: 10px; /* Extra ruimte rondom tekst */\n"
"    font-size: 16px; /* Tekstgrootte */\n"
"    font-weight: bold;\n"
"    color: white; /* Tekstkleur */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    opacity: 0.8; /* Iets transparanter bij hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 0.2); /* Donkere overlay bij klikken */\n"
"}\n"
"")
        self.herstart_quiz.setText("")
        self.herstart_quiz.setObjectName("herstart_quiz")
        self.widget_10 = QtWidgets.QWidget(self.page_3)
        self.widget_10.setGeometry(QtCore.QRect(0, 210, 741, 311))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(26)
        self.widget_10.setFont(font)
        self.widget_10.setStyleSheet("QWidget {\n"
"    background-color: #6a6db6;  /* Lichtere versie van #4549a0 */\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: cover;  /* Zorgt ervoor dat de afbeelding de hele achtergrond bedekt */\n"
"}\n"
"")
        self.widget_10.setObjectName("widget_10")
        self.score_gebruiker = QtWidgets.QLabel(self.widget_10)
        self.score_gebruiker.setGeometry(QtCore.QRect(380, 50, 291, 91))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(18)
        self.score_gebruiker.setFont(font)
        self.score_gebruiker.setStyleSheet("QLabel {\n"
"    border: none;  /* Verwijder de rand */\n"
"\n"
"    color: white;  /* Zet de tekstkleur op wit voor de ingevulde tekst */\n"
"    padding: 5px;  /* Voeg wat padding toe voor de tekst */\n"
"    border-radius: 5px;  /* Maak de hoeken van de QLineEdit iets ronder */\n"
"}")
        self.score_gebruiker.setText("")
        self.score_gebruiker.setObjectName("score_gebruiker")
        self.label_11 = QtWidgets.QLabel(self.widget_10)
        self.label_11.setGeometry(QtCore.QRect(12, 10, 41, 51))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel {\n"
"    color: #d4a017; /* Donkerder goud, pixelachtig */\n"
"    \n"
"    \n"
"}\n"
"\n"
"\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(False)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.widget_10)
        self.label_12.setGeometry(QtCore.QRect(13, 58, 41, 51))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel {\n"
"    color: #a6a6a6; /* Oudere zilverkleur, meer pixelstijl */\n"
"    \n"
"\n"
"}\n"
"")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setWordWrap(False)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.widget_10)
        self.label_13.setGeometry(QtCore.QRect(12, 110, 41, 41))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("\n"
"QLabel {\n"
"    color: #b87333; /* Oudere bronskleur */\n"
"    \n"
"\n"
"}\n"
"")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setWordWrap(False)
        self.label_13.setObjectName("label_13")
        self.topscore_1 = QtWidgets.QLabel(self.widget_10)
        self.topscore_1.setGeometry(QtCore.QRect(50, 20, 250, 31))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(18)
        self.topscore_1.setFont(font)
        self.topscore_1.setStyleSheet("QLabel {\n"
"    color: #d4a017; /* Donkerder goud, pixelachtig */\n"
"    \n"
"    \n"
"}")
        self.topscore_1.setText("")
        self.topscore_1.setObjectName("topscore_1")
        self.topscore_2 = QtWidgets.QLabel(self.widget_10)
        self.topscore_2.setGeometry(QtCore.QRect(50, 70, 250, 31))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(18)
        self.topscore_2.setFont(font)
        self.topscore_2.setStyleSheet("QLabel {\n"
"    color: #a6a6a6; /* Oudere zilverkleur, meer pixelstijl */\n"
"    \n"
"\n"
"}\n"
"")
        self.topscore_2.setText("")
        self.topscore_2.setObjectName("topscore_2")
        self.topscore_3 = QtWidgets.QLabel(self.widget_10)
        self.topscore_3.setGeometry(QtCore.QRect(50, 117, 250, 31))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(18)
        self.topscore_3.setFont(font)
        self.topscore_3.setStyleSheet("\n"
"QLabel {\n"
"    color: #b87333; /* Oudere bronskleur */\n"
"    \n"
"\n"
"}\n"
"")
        self.topscore_3.setText("")
        self.topscore_3.setObjectName("topscore_3")
        self.label_14 = QtWidgets.QLabel(self.widget_10)
        self.label_14.setGeometry(QtCore.QRect(371, 15, 191, 41))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(18)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel {\n"
"    border: none;  /* Verwijder de rand */\n"
"\n"
"    color: white;  /* Zet de tekstkleur op wit voor de ingevulde tekst */\n"
"    padding: 5px;  /* Voeg wat padding toe voor de tekst */\n"
"    border-radius: 5px;  /* Maak de hoeken van de QLineEdit iets ronder */\n"
"}")
        self.label_14.setObjectName("label_14")
        StackedWidget.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.widget_11 = QtWidgets.QWidget(self.page)
        self.widget_11.setGeometry(QtCore.QRect(0, 0, 741, 211))
        self.widget_11.setStyleSheet("QWidget {\n"
"    background-color: black;  /* Lichtere versie van #4549a0 */\n"
"}\n"
"")
        self.widget_11.setObjectName("widget_11")
        self.verberg_page4 = QtWidgets.QPushButton(self.widget_11)
        self.verberg_page4.setGeometry(QtCore.QRect(640, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        self.verberg_page4.setFont(font)
        self.verberg_page4.setStyleSheet("QPushButton {\n"
"    background-color: #6a6db6;  /* Lichtere versie van #4549a0 */\n"
"}\n"
"")
        self.verberg_page4.setObjectName("verberg_page4")
        self.close_page4 = QtWidgets.QPushButton(self.widget_11)
        self.close_page4.setGeometry(QtCore.QRect(690, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        self.close_page4.setFont(font)
        self.close_page4.setStyleSheet("QPushButton {\n"
"    background-color: #6a6db6;  /* Lichtere versie van #4549a0 */\n"
"}\n"
"")
        self.close_page4.setObjectName("close_page4")
        self.widget_12 = QtWidgets.QWidget(self.widget_11)
        self.widget_12.setGeometry(QtCore.QRect(-29, 10, 351, 171))
        self.widget_12.setStyleSheet("QWidget {\n"
"    background-image: url(\"images/feedback_logo.png\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: cover;  /* Zorgt ervoor dat de afbeelding de hele achtergrond vult */\n"
"}\n"
"")
        self.widget_12.setObjectName("widget_12")
        self.widget_13 = QtWidgets.QWidget(self.widget_11)
        self.widget_13.setGeometry(QtCore.QRect(321, 4, 121, 111))
        self.widget_13.setStyleSheet("QWidget {\n"
"    background-image: url(\"images/Macintosh_Games_-_RetroWeb_Vintage_Computer_Museum.jpg\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: cover;  /* Zorgt ervoor dat de afbeelding de hele achtergrond vult */\n"
"}\n"
"")
        self.widget_13.setObjectName("widget_13")
        self.feedback_button_2 = QtWidgets.QPushButton(self.widget_11)
        self.feedback_button_2.setGeometry(QtCore.QRect(570, 100, 81, 71))
        self.feedback_button_2.setStyleSheet("QPushButton {\n"
"    background-image: url(\"images/feedback_logo.jpg\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: cover;  /* Zorgt ervoor dat de afbeelding de hele achtergrond vult */\n"
"}")
        self.feedback_button_2.setText("")
        self.feedback_button_2.setObjectName("feedback_button_2")
        self.widget_14 = QtWidgets.QWidget(self.page)
        self.widget_14.setGeometry(QtCore.QRect(0, 210, 741, 311))
        self.widget_14.setStyleSheet("QWidget {\n"
"    background-color: #6a6db6;  /* Lichtere versie van #4549a0 */\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: cover;  /* Zorgt ervoor dat de afbeelding de hele achtergrond bedekt */\n"
"}\n"
"")
        self.widget_14.setObjectName("widget_14")
        self.foute_vraag = QtWidgets.QLabel(self.widget_14)
        self.foute_vraag.setGeometry(QtCore.QRect(10, 10, 721, 71))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(20)
        self.foute_vraag.setFont(font)
        self.foute_vraag.setStyleSheet("QLabel {\n"
"    border: none;  /* Verwijder de rand */\n"
"\n"
"    color: white; /* Zet de tekstkleur op wit voor de ingevulde tekst */\n"
"    padding: 5px;  /* Voeg wat padding toe voor de tekst */\n"
"    border-radius: 5px;  /* Maak de hoeken van de QLineEdit iets ronder */\n"
"}")
        self.foute_vraag.setText("")
        self.foute_vraag.setWordWrap(True)
        self.foute_vraag.setObjectName("foute_vraag")
        self.juiste_antwoord = QtWidgets.QLabel(self.widget_14)
        self.juiste_antwoord.setGeometry(QtCore.QRect(10, 90, 721, 81))
        font = QtGui.QFont()
        font.setFamily("RuneScape UF")
        font.setPointSize(20)
        self.juiste_antwoord.setFont(font)
        self.juiste_antwoord.setStyleSheet("QLabel {\n"
"    border: none;  /* Verwijder de rand */\n"
"\n"
"    color: black; /* Zet de tekstkleur op wit voor de ingevulde tekst */\n"
"    padding: 5px;  /* Voeg wat padding toe voor de tekst */\n"
"    border-radius: 5px;  /* Maak de hoeken van de QLineEdit iets ronder */\n"
"}")
        self.juiste_antwoord.setText("")
        self.juiste_antwoord.setWordWrap(True)
        self.juiste_antwoord.setObjectName("juiste_antwoord")
        StackedWidget.addWidget(self.page)

        self.retranslateUi(StackedWidget)
        StackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(StackedWidget)

    def retranslateUi(self, StackedWidget):
        _translate = QtCore.QCoreApplication.translate
        StackedWidget.setWindowTitle(_translate("StackedWidget", "StackedWidget"))
        self.verberg_page1.setText(_translate("StackedWidget", "--"))
        self.close_page1.setText(_translate("StackedWidget", "X"))
        self.label.setText(_translate("StackedWidget", "Naam:"))
        self.naam_input.setText(_translate("StackedWidget", "Vul je naam in:"))
        self.label_2.setText(_translate("StackedWidget", "Thema:"))
        self.onderwerp_input.setItemText(0, _translate("StackedWidget", "Keuze thema:"))
        self.onderwerp_input.setItemText(1, _translate("StackedWidget", "geschiedenis"))
        self.onderwerp_input.setItemText(2, _translate("StackedWidget", "sport"))
        self.onderwerp_input.setItemText(3, _translate("StackedWidget", "cultuur"))
        self.onderwerp_input.setItemText(4, _translate("StackedWidget", "filosofie"))
        self.label_3.setText(_translate("StackedWidget", "Moeilijkheid:"))
        self.moeilijkheid_input.setItemText(0, _translate("StackedWidget", "Keuze niveau:"))
        self.moeilijkheid_input.setItemText(1, _translate("StackedWidget", "gevorderd"))
        self.moeilijkheid_input.setItemText(2, _translate("StackedWidget", "medium"))
        self.moeilijkheid_input.setItemText(3, _translate("StackedWidget", "beginner"))
        self.label_4.setText(_translate("StackedWidget", "Aantal vragen:"))
        self.comboBox.setItemText(0, _translate("StackedWidget", "5"))
        self.comboBox.setItemText(1, _translate("StackedWidget", "10"))
        self.label_5.setText(_translate("StackedWidget", "Willekeurig:"))
        self.verberg_page2.setText(_translate("StackedWidget", "--"))
        self.close_page2.setText(_translate("StackedWidget", "X"))
        self.verberg_page3.setText(_translate("StackedWidget", "--"))
        self.close_page3.setText(_translate("StackedWidget", "X"))
        self.label_11.setText(_translate("StackedWidget", "1"))
        self.label_12.setText(_translate("StackedWidget", "2"))
        self.label_13.setText(_translate("StackedWidget", "3"))
        self.label_14.setText(_translate("StackedWidget", "Jouw score:"))
        self.verberg_page4.setText(_translate("StackedWidget", "--"))
        self.close_page4.setText(_translate("StackedWidget", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StackedWidget = QtWidgets.QStackedWidget()
    ui = Ui_StackedWidget()
    ui.setupUi(StackedWidget)
    StackedWidget.show()
    sys.exit(app.exec_())
